// Autogenerated from Pigeon (v7.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, SPVisualisationType) {
  SPVisualisationTypeTable = 0,
  SPVisualisationTypeChart = 1,
};

@class SPVisualisation;

@interface SPVisualisation : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithVisualisationType:(SPVisualisationType)visualisationType;
@property(nonatomic, assign) SPVisualisationType visualisationType;
@end

/// The codec used by SPFlutterStockApi.
NSObject<FlutterMessageCodec> *SPFlutterStockApiGetCodec(void);

@interface SPFlutterStockApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)chooseVisualisationTypeVisualisation:(SPVisualisation *)visualisation completion:(void (^)(NSError *_Nullable))completion;
@end

/// The codec used by SPHostNavigationApi.
NSObject<FlutterMessageCodec> *SPHostNavigationApiGetCodec(void);

@protocol SPHostNavigationApi
- (void)goBackWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SPHostNavigationApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SPHostNavigationApi> *_Nullable api);

NS_ASSUME_NONNULL_END
