// Autogenerated from Pigeon (v7.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, VisualisationType) {
  VisualisationTypeTable = 0,
  VisualisationTypeChart = 1,
};

@class Visualisation;

@interface Visualisation : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithVisualisationType:(VisualisationType)visualisationType;
@property(nonatomic, assign) VisualisationType visualisationType;
@end

/// The codec used by FlutterStockApi.
NSObject<FlutterMessageCodec> *FlutterStockApiGetCodec(void);

@interface FlutterStockApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)displayStockDataVisualisation:(Visualisation *)visualisation completion:(void (^)(NSError *_Nullable))completion;
@end

/// The codec used by NativeNavigationApi.
NSObject<FlutterMessageCodec> *NativeNavigationApiGetCodec(void);

@protocol NativeNavigationApi
- (void)goBackWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void NativeNavigationApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NativeNavigationApi> *_Nullable api);

NS_ASSUME_NONNULL_END
