// Autogenerated from Pigeon (v7.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "api.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface SPVisualisation ()
+ (SPVisualisation *)fromList:(NSArray *)list;
+ (nullable SPVisualisation *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation SPVisualisation
+ (instancetype)makeWithVisualisationType:(SPVisualisationType)visualisationType {
  SPVisualisation* pigeonResult = [[SPVisualisation alloc] init];
  pigeonResult.visualisationType = visualisationType;
  return pigeonResult;
}
+ (SPVisualisation *)fromList:(NSArray *)list {
  SPVisualisation *pigeonResult = [[SPVisualisation alloc] init];
  pigeonResult.visualisationType = [GetNullableObjectAtIndex(list, 0) integerValue];
  return pigeonResult;
}
+ (nullable SPVisualisation *)nullableFromList:(NSArray *)list {
  return (list) ? [SPVisualisation fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.visualisationType),
  ];
}
@end

@interface SPFlutterStockApiCodecReader : FlutterStandardReader
@end
@implementation SPFlutterStockApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [SPVisualisation fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface SPFlutterStockApiCodecWriter : FlutterStandardWriter
@end
@implementation SPFlutterStockApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[SPVisualisation class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface SPFlutterStockApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation SPFlutterStockApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[SPFlutterStockApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[SPFlutterStockApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *SPFlutterStockApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    SPFlutterStockApiCodecReaderWriter *readerWriter = [[SPFlutterStockApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface SPFlutterStockApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation SPFlutterStockApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)chooseVisualisationTypeVisualisation:(SPVisualisation *)arg_visualisation completion:(void (^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.FlutterStockApi.chooseVisualisationType"
      binaryMessenger:self.binaryMessenger
      codec:SPFlutterStockApiGetCodec()];
  [channel sendMessage:@[arg_visualisation ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

NSObject<FlutterMessageCodec> *SPHostNavigationApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SPHostNavigationApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SPHostNavigationApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HostNavigationApi.goBack"
        binaryMessenger:binaryMessenger
        codec:SPHostNavigationApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(goBackWithError:)], @"SPHostNavigationApi api (%@) doesn't respond to @selector(goBackWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api goBackWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
