# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../variacao_ativa_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'variacao-ativa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  install_all_flutter_pods(flutter_application_path)

  # Pods for variacao-ativa
  pod 'Alamofire'
  pod 'iOSDropDown'
  
  target 'variacao-ativaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'variacao-ativaUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
