// Autogenerated from Pigeon (v7.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum VisualisationType {
  table,
  chart,
}

class Visualisation {
  Visualisation({
    required this.visualisationType,
  });

  VisualisationType visualisationType;

  Object encode() {
    return <Object?>[
      visualisationType.index,
    ];
  }

  static Visualisation decode(Object result) {
    result as List<Object?>;
    return Visualisation(
      visualisationType: VisualisationType.values[result[0]! as int],
    );
  }
}

class _FlutterStockApiCodec extends StandardMessageCodec {
  const _FlutterStockApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Visualisation) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return Visualisation.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterStockApi {
  static const MessageCodec<Object?> codec = _FlutterStockApiCodec();

  void chooseVisualisationType(Visualisation visualisation);

  static void setup(FlutterStockApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterStockApi.chooseVisualisationType', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterStockApi.chooseVisualisationType was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Visualisation? arg_visualisation = (args[0] as Visualisation?);
          assert(arg_visualisation != null,
              'Argument for dev.flutter.pigeon.FlutterStockApi.chooseVisualisationType was null, expected non-null Visualisation.');
          api.chooseVisualisationType(arg_visualisation!);
          return;
        });
      }
    }
  }
}

class HostNavigationApi {
  /// Constructor for [HostNavigationApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HostNavigationApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  Future<void> goBack() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.HostNavigationApi.goBack', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}
