name: stock_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  yahoo_finance_api:
    path: ../yahoo_finance_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  

flutter:
